### ISSUE TITLE
Unable to access my assets on the platform. 

### ISSUE THREAD

**Issue by teamcryptousa** [UnFederalReserve/community#98] opened 2021-09-10 20:25 UTC
**Describe the bug**
I normally link to UnFederalReserve lending platform via Trust wallet. I tried loggin in on 2 devices and it's saying "no assets supplied." I have the unfederalreserve assets in my wallet. Nothing is displaying on the platform. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/82060595/132913127-860dddbe-8020-417f-9efa-5009ff504004.png)

**Desktop (please complete the following information):**
 - OS: Tried on Chrome and Safari
 - Browser Chrome and Safari

**Wallet Version (please complete the following information):**
 - Wallet: Trust Wallet
 - Public Address: 0x9975653EcfA9a4409DC291E67Ba938C5B7366092

**Additional context**

**Comment by hskainth** [comment] 2021-09-10 23:57
@teamcryptousa thanks for reporting issue, internal issue 1209 has been raised for this.

**Comment by fizzyfoss26** [comment] 2021-09-11 23:27
Any updates here?

**Comment by teamcryptousa** [comment] 2021-09-11 23:32
I still don’t have access today

**Comment by hskainth** [comment] 2021-09-16 17:28
@fizzyfoss26 @teamcryptousa are you still experiencing this as we cannot reproduce?

**Comment by teamcryptousa** [comment] 2021-09-16 21:04
No. It’s working now. Thanks for the follow up.

**Comment by hskainth** [comment] 2021-09-16 22:33
Closing issue as per above comment.

**Closed as completed by hskainth** 2021-09-16 22:33 UTC
Labels: bug

**Comment by teamcryptousa** [comment] 2021-11-03 20:20
My supplied USDC isn't showing up in my wallet again. It's been going on
for a couple of days. This is the second time this has happened. Can you
please look at it?
My Wallet Address is:

0x9975653EcfA9a4409DC291E67Ba938C5B7366092

[image: image.png]

**Comment by hskainth** [comment] 2021-11-03 21:02
@teamcryptousa this should now show.

**Comment by teamcryptousa** [comment] 2021-11-03 21:05
It's working now. Thank you.
