### ISSUE TITLE
UnReserveLending Page showing "No assets supplied" but my rewards are still visible

### ISSUE THREAD

**Issue by fizzyfoss26** [UnFederalReserve/community#99] opened 2021-09-11 18:38 UTC
**Describe the bug**
UnReserveLending Page showing "No Assets Supplied" but my rewards are still visible
**To Reproduce**

1. Go to https://lending.unfederalreserve.com/
2. Connect Coinbase Wallet
3. Under My Supply, see "No assets supplied"

**Expected behavior**
My full supply should show.

**Screenshots**

**Wallet Version (please complete the following information):**
 - Wallet: Coinbase]
 - Public Address: [e.g. 0xB4C76be44c6DC6C3dD739835002572cA87594db1
<img width="1062" alt="Screen Shot 2021-09-11 at 2 17 31 PM" src="https://user-images.githubusercontent.com/90526709/132957930-1136b1b7-2b83-460c-9e59-b944076a59dc.png">
]

**Additional context**

**Comment by hskainth** [comment] 2021-09-11 21:44
@fizzyfoss26 closing as duplicate of issue #98

**Closed as completed by hskainth** 2021-09-11 21:44 UTC
Labels: bug
