### ISSUE TITLE
Lending platform will not load

### ISSUE THREAD

**Issue by paulmc90** [UnFederalReserve/community#87] opened 2021-07-08 23:16 UTC
**Describe the bug**
When i click to connect coinbase wallet on lending platform it gets stuck on the loading page (the boat screen). Sometimes it gets to the QR code, when i scan the QR code on my phone my wallet connects but the QR code scan box does not remove itself from the page and it cannot be closed, at this point i cannot get any further. My phone confirms my wallet is connected but the lending platform does not reflect this, the QR scan pop up cannot be closed.

**To Reproduce**
1. Go to 'https://unfederalreserve.com/'
2. Click on 'Lending'
3. IF I get to the 'select wallet' screen I Select coinbase wallet
4. IF i get passed the loading page the QR code appears, I scan with coinbase wallet, I can see my wallet address on the platform but no lending figures and the QR code does not go away. At this point I cannot go any further.

Alternate path:
1. Go to 'https://unfederalreserve.com/'
2. Click on 'Lending'
3. Close 'select wallet' screen.
4. Select 'Unlock Wallet' - this shows the screenshot attached.

**Expected behavior**
I have connected the coinbase wallet multiple times since launch without issue, in the last two weeks it has been having issues. When i have scanned the QR code in the past the dashboard loads showing my supply/borrow etc.

**Screenshots**
![Capture 1](https://user-images.githubusercontent.com/83785746/125001471-9be80880-e007-11eb-84ab-776e3e041859.PNG)

QR code pop up does not go away after wallet connection.
![bf4fa11a-1960-4eb2-b892-d2295bab56ba](https://user-images.githubusercontent.com/83785746/125002448-cb981000-e009-11eb-93fb-66fe40a2881e.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome
 - Version : Version 91.0.4472.124 (Official Build) (64-bit)

**Wallet Version (please complete the following information):**
 - Wallet: Coinbase
 - Public Address: 0xB4123700A736a786358b9B33d29d953332b637fd

**Additional context**

**Comment by hskainth** [comment] 2021-07-12 17:25
@paulmc90 are you still experiencing this?

**Comment by paulmc90** [comment] 2021-07-12 17:29
Yeah this is still going on, I have found that it works properly when using Incognito mode on google chrome.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by hskainth** [comment] 2021-07-14 09:38
Internal issue 800 raised to investigate this.

**Comment by hskainth** [comment] 2021-07-20 16:09
This worked fine when tested internally both incognito and normal mode. 

Closing issue as unable to reproduce and user is able to log in using icognito mode.

**Closed by hskainth** 2021-07-20 16:09 UTC
Labels: bug
